# Generated by Django 3.1.7 on 2021-04-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='Award/')),
            ],
            options={
                'verbose_name': '荣誉',
                'verbose_name_plural': '荣誉',
                'db_table': 'Award',
            },
        ),
    ]
