# Generated by Django 3.1.7 on 2021-04-02 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='产品名称')),
                ('photo', models.ImageField(blank=True, upload_to='Product/', verbose_name='产品图片')),
                ('description', models.TextField(verbose_name='产品描述')),
                ('productType', models.CharField(choices=[('家用机器人', '家用机器人'), ('智能门锁', '智能门锁'), ('人脸识别解决方案', '人脸识别解决方案')], max_length=100, verbose_name='产品类型')),
                ('price', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('publishDate', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='发布时间')),
                ('views', models.PositiveIntegerField(default=1, max_length=20, verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'ordering': ('-publishDate',),
            },
        ),
    ]
