# Generated by Django 3.1.7 on 2021-04-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mynew',
            options={'ordering': ['-publish_date'], 'verbose_name': '新闻', 'verbose_name_plural': '新闻'},
        ),
        migrations.AlterField(
            model_name='mynew',
            name='newType',
            field=models.CharField(choices=[('企业要闻', '企业要闻'), ('行业新闻', '行业新闻'), ('通知公告', '通知公告')], max_length=50, verbose_name='新闻类型'),
        ),
        migrations.AlterField(
            model_name='mynew',
            name='views',
            field=models.PositiveIntegerField(default=1, verbose_name='浏览量'),
        ),
    ]
