# Generated by Django 3.1.7 on 2021-04-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0002_auto_20210404_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynew',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='展报'),
        ),
    ]
